### ISSUE TITLE
Discord Portage

### ISSUE THREAD

**Issue by Lymdun** [Julien00859/BotIRC#4]
? c:

**Comment by Julien00859** [comment]
Ce bot-ci suit la [RFC 1459](https://tools.ietf.org/html/rfc1459) donc je dois tout refaire, puis il y a toute une série de fonctionnalité présentes dans discord qui ne le sont pas dans IRC donc l'api aussi je vais devoir la refaire. Bref, c'est pas au goût du jour pour moi :p

Sinon sur notre discord on utilise celui-là (dev par nous) https://github.com/SalonDesDevs/Shenron
